    <table class="table table-hover">
    <caption></caption>
    <thead>
    <tr>
    <th>Movie Name</th>
    <th>Movie Story</th>
    <th>Options</th>
    </tr>
    </thead>
    <tbody>
    	<?php 
foreach ($this->result as $key => $value) {
			echo "<tr><td>$value[title]</td><td>$value[story]</td>";
			echo "<td><a href='update/id/$value[id]/?title=$value[title]&story=$value[story]'>Update</a> | <a href='delete/id/$value[id]/'>Delete</a></td></tr>";
} ?>  

    </tbody>
    </table>